[package]
name = "metar-pars"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
nom = "7.1.3"

[dev-dependencies]
criterion = "0.5.1"
metar = "0.7.7"
reqwest = { version = "0.12.4", features = ["blocking"] }

[[bench]]
name = "metars_bench"
harness = false
